#hibernate configuration
spring:
  jpa:
    hibernate:
      ddl-auto : update
      show-sql : true
      format-sql : true
      dialect : org.hibernate.dialect.MySQL8Dialect

#eureka-configuration
eureka:
  instance:
    prefer-ip-address : true
  client:
    register-with-eureka : true
    fetch-registry : true
    service-url:
      defaultZone : http://localhost:8281/eureka

